import type { Person } from "./people-types";

export const samplePeople: Person[] = [
  {
    id: 1,
    name: "Alex Morgan",
    title: "Software Engineer",
    headline: "Building scalable frontend systems",
    linkedinUrl: "linkedin.com/in/alexmorgan",
    company: "Bitscale",
    companyUrl: "bitscale.ai",
    location: "United States",
    companyLocation: "United States",
    companyHeadcount: "11-50",
    managementLevel: "Employee",
  },
  {
    id: 2,
    name: "Sarah Wilson",
    title: "Senior Software Engineer",
    headline: "Backend and cloud systems at scale",
    linkedinUrl: "linkedin.com/in/sarahwilson",
    company: "HubSpot",
    companyUrl: "hubspot.com",
    location: "UAE",
    companyLocation: "UAE",
    companyHeadcount: "10000+",
    managementLevel: "Manager",
  },
  {
    id: 3,
    name: "Chris Parker",
    title: "Product Manager",
    headline: "Founder building AI workflow tools",
    linkedinUrl: "linkedin.com/in/chrisparker",
    company: "ScaleFlow",
    companyUrl: "scaleflow.io",
    location: "London",
    companyLocation: "United Kingdom",
    companyHeadcount: "1-10",
    managementLevel: "Founder",
  },
  {
    id: 4,
    name: "Jane Doe",
    title: "UX Designer",
    headline: "Design systems and product experience",
    linkedinUrl: "linkedin.com/in/janedoe",
    company: "Google",
    companyUrl: "google.com",
    location: "United States",
    companyLocation: "United States",
    companyHeadcount: "10000+",
    managementLevel: "Manager",
  },
  {
    id: 5,
    name: "Mohammed Ali",
    title: "Data Scientist",
    headline: "ML pipelines and analytics",
    linkedinUrl: "linkedin.com/in/mohammedali",
    company: "LinkedIn",
    companyUrl: "linkedin.com",
    location: "UAE",
    companyLocation: "UAE",
    companyHeadcount: "1000-5000",
    managementLevel: "Director",
  },
  {
    id: 6,
    name: "Emma Brown",
    title: "DevOps Engineer",
    headline: "Cloud infra and deployment automation",
    linkedinUrl: "linkedin.com/in/emmabrown",
    company: "Amazon",
    companyUrl: "amazon.com",
    location: "London",
    companyLocation: "United Kingdom",
    companyHeadcount: "10000+",
    managementLevel: "Employee",
  },
];

export const filterOptions = {
  jobTitle: [
    "Software Engineer",
    "Senior Software Engineer",
    "Product Manager",
    "UX Designer",
    "Data Scientist",
    "DevOps Engineer",
  ],
  companyWebsite: [
    "bitscale.ai",
    "hubspot.com",
    "scaleflow.io",
    "google.com",
    "linkedin.com",
    "amazon.com",
  ],
  personLocation: ["United States", "UAE", "London"],
  companyLocation: ["United States", "UAE", "United Kingdom"],
  companyHeadcount: ["1-10", "11-50", "1000-5000", "10000+"],
  managementLevel: ["Employee", "Manager", "Director", "Founder"],
};